/* eslint-disable react-hooks/rules-of-hooks */
import { Flex, Heading } from "@chakra-ui/layout";
import React, { useContext, useEffect, useState } from "react";
import useWindowSize from "../src/CustomHooks/UseWindows";
import Colors from "../src/Constants/Colors";
import { Spacer } from "@chakra-ui/layout";
import NavLoginButtonContext from "../src/Context/NavLogInButtonContext";
import UserInformations from "../src/Components/dashboard/UserInformations";
import axios from "axios";
import UserDataContext from "../src/Context/UserDataContext";
import Router from "next/router";
import Head from "next/head";
import NavigationBar from "../src/Components/dashboard/NavigationBar";
export default function dashboard(props) {
  const getWindowSize = useWindowSize();
  const userDataContext = useContext(UserDataContext);
  const navLoginButtonContext = useContext(NavLoginButtonContext);

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar />
      <Flex flexDirection="row"  autoFocus {...styleProps.dashboardWrapper}>
        {getWindowSize.width < 960 ? (
          <Heading>Mobile Devices are not supported</Heading>
        ) : (
          <>
             
            <Flex flexDirection="column">
            </Flex>
          </>
        )}
      </Flex>
    </>
  );
}


const styleProps = {
  dashboardWrapper: {
    alignItems: "flex-start",
    justifyContent: "center",
    padding: "10",
    bgColor: Colors.black,
    h:"87.8vh",
  },
};
