import React from 'react';
import { Heading, Flex, Button, Stack, HStack,} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import Colors from "../src/Constants/Colors";
import useWindowSize from "../src/CustomHooks/UseWindows";
import Router from "next/router";

export default function Home() {
  const getWindowSize = useWindowSize();
  async function loadToLogin() {
    Router.push("/login")
    };
  return (
    <>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex {...styleProps.indexWrapper}>
        <Image
          src={"/tyto.png"}
          alt="Picture of the author"
          width={500}
          height={400}
        />
        <Flex flexDirection={getWindowSize.width < 960 ? "column" : "row"}>
          <HStack>
            <Heading>LEARN</Heading>
            <Heading>BETTER </Heading>
            <Heading>TOGETHER</Heading>
          </HStack>
        </Flex>
        <Flex
          flexDirection={getWindowSize.width < 960 ? "column" : "row"}
          marginTop="10"
        >
        <Stack isInline justifyContent= 'space-between'>
          <Button
            variant="solid"
            backgroundColor={Colors.green}
            color={Colors.white}
            colorScheme="cyan"
            onClick={loadToLogin}
          >
            START NOW!
          </Button>
          </Stack>
        </Flex>
      </Flex>
    </>
  );
}

const styleProps = {
  indexWrapper: {
    height: "100vh",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    bgColor: Colors.white,
  },
};